### PR TITLE
feat: add web support

### LINKED ISSUE #20: feat: add web support
**Is your feature request related to a problem? Please describe:**

Web platform is currently not supported.

**Describe the solution you'd like:**

Add support for the web platform.

### PR DESCRIPTION
**Pull request by robingenz**
Close robingenz/capacitor-firebase-authentication#20

### CODE REVIEW

**Comment by ThcDelux3** [comment]
Awesome going to check Web support this evening. 💯

**Comment by robingenz** [comment]
Glad to hear it!
Let me know if you have any problems.

**Comment by ThcDelux3** [comment]
Works flawlessly. Maybe wanna add my VueJS example to the Readme? I'm currently writing a Medium article for the plugin I hope this is fine for you?

## Usage

<details>
  <summary>VueJs</summary>

```typescript
import { FirebaseAuthentication } from '@robingenz/capacitor-firebase-authentication';

export default {
    name: 'FirebaseAuthentication',

    components: {
        //
    },

    data() {
        return {
            //
        };
    },
    
    methods: {

        async getCurrentUser () {
            const result = await FirebaseAuthentication.getCurrentUser();
            return result.user;
        },

        async getIdToken () {
            const result = await FirebaseAuthentication.getIdToken();
            return result.token;
        },

        async setLanguageCode () {
            await FirebaseAuthentication.setLanguageCode({ languageCode: 'en-US' });
        },

        async signInWithApple () {
            await FirebaseAuthentication.signInWithApple();
        },

        async signInWithFacebook () {
            await FirebaseAuthentication.signInWithFacebook();
        },

        async signInWithGithub () {
            await FirebaseAuthentication.signInWithGithub();
        },

        async signInWithGoogle () {
            await FirebaseAuthentication.signInWithGoogle();
        },

        async signInWithMicrosoft () {
            await FirebaseAuthentication.signInWithMicrosoft();
        },

        async signInWithPhoneNumber () {
            const { verificationId } = await FirebaseAuthentication.signInWithPhoneNumber(
                {
                    phoneNumber: '123456789',
                },
            );
            const verificationCode = window.prompt(
                'Please enter the verification code that was sent to your mobile device.',
            );
            await FirebaseAuthentication.signInWithPhoneNumber({
                verificationId,
                verificationCode,
            });
        },

        async signInWithTwitter () {
            await FirebaseAuthentication.signInWithTwitter();
        },

        async signInWithYahoo () {
            await FirebaseAuthentication.signInWithYahoo();
        },

        async signOut () {
            await FirebaseAuthentication.signOut();
        },

        async useAppLanguage () {
            await FirebaseAuthentication.useAppLanguage();
        }

    }

};  
```

</details>

<details>
  <summary>Angular</summary>

```typescript
import { FirebaseAuthentication } from '@robingenz/capacitor-firebase-authentication';

const getCurrentUser = async () => {
  const result = await FirebaseAuthentication.getCurrentUser();
  return result.user;
};

const getIdToken = async () => {
  const result = await FirebaseAuthentication.getIdToken();
  return result.token;
};

const setLanguageCode = async () => {
  await FirebaseAuthentication.setLanguageCode({ languageCode: 'en-US' });
};

const signInWithApple = async () => {
  await FirebaseAuthentication.signInWithApple();
};

const signInWithFacebook = async () => {
  await FirebaseAuthentication.signInWithFacebook();
};

const signInWithGithub = async () => {
  await FirebaseAuthentication.signInWithGithub();
};

const signInWithGoogle = async () => {
  await FirebaseAuthentication.signInWithGoogle();
};

const signInWithMicrosoft = async () => {
  await FirebaseAuthentication.signInWithMicrosoft();
};

const signInWithPhoneNumber = async () => {
  const { verificationId } = await FirebaseAuthentication.signInWithPhoneNumber(
    {
      phoneNumber: '123456789',
    },
  );
  const verificationCode = window.prompt(
    'Please enter the verification code that was sent to your mobile device.',
  );
  await FirebaseAuthentication.signInWithPhoneNumber({
    verificationId,
    verificationCode,
  });
};

const signInWithTwitter = async () => {
  await FirebaseAuthentication.signInWithTwitter();
};

const signInWithYahoo = async () => {
  await FirebaseAuthentication.signInWithYahoo();
};

const signOut = async () => {
  await FirebaseAuthentication.signOut();
};

const useAppLanguage = async () => {
  await FirebaseAuthentication.useAppLanguage();
};
```

</details>

**Comment by robingenz** [comment]
Glad to hear that!
Of course that's fine, thank you! I would love to read the article then.

The code in [Usage](https://github.com/robingenz/capacitor-firebase-authentication#usage) is not framework-specific code. Just basic JavaScript examples.
So VueJS specific code doesn't fit in there very well.
But i would love to add a demo app to the `README.md` (like [here](https://github.com/robingenz/capacitor-firebase-performance#demo)).
Feel free to create a Vue app and send me the link.

**Comment by Mikkoun** [comment]
Will there be a signInWithPhoneNumber support for web?

**Pull request merged**
