### PR TITLE
feat(android): support Play Games sign-in

### LINKED ISSUE #80: feat: Google Play Services support
Not sure how Google Play Services rates in popularity to the other methods of authentication this plugin could integrate, but I can confidently say that supporting it would reopen the door to developing Android games in Javascript. Direct plugins to GPS have fallen by the wayside in recent years:

https://github.com/artberri/cordova-plugin-play-games-services
https://github.com/openforge/capacitor-game-services

And yet, you'd be hard pressed to find an Android game that doesn't use it. My story is of developing a Javascript game over many years, hoping for platform ubiquity, and missing out due to this hole in Google integration.

### PR DESCRIPTION
**Pull request by robingenz**
Close #80

### CODE REVIEW

**Comment by robingenz** [comment]
Hi @erikwalle,
As discussed, I would be happy if you could test the Play Games Sign-In.
I created a dev build:

```
npm i @robingenz/capacitor-firebase-authentication@0.3.9-dev.85df3b7.1631040531
```

This is the setup guide: https://github.com/robingenz/capacitor-firebase-authentication/blob/85df3b7baa28db64d4506a0ec7b8aeac2529d772/docs/setup-play-games.md

Sign-In with Play Games should then work as follows:

```ts
import { FirebaseAuthentication } from '@robingenz/capacitor-firebase-authentication';

const signInWithPlayGames = async () => {
  await FirebaseAuthentication.signInWithPlayGames();
};
```

I look forward to your feedback! Thank you very much!

**Comment by robingenz** [comment]
I recommend using the [`providers` configuration option](https://github.com/robingenz/capacitor-firebase-authentication/tree/85df3b7baa28db64d4506a0ec7b8aeac2529d772#configuration) and enabling only `playgames.google.com` as there is currently a bug with the Facebook provider (#64).

**Comment by erikwalle** [comment]
Hi @robingenz , I can get to this in a week or so.

My current GPS integration depends on hooks for achievements and leaderboards. There are calls to progress achievements, submit scores, and trigger native views of each. About 5 different endpoints. Is that something you'd be interested in adding?

Eg.: https://github.com/openforge/capacitor-game-services/blob/development/android/src/main/java/io/openforge/gameservices/GameServices.java#L110

Lmk, thanks.

**Comment by robingenz** [comment]
Hi @erikwalle,
that sounds good, thank you.

In my opinion, these are not functionalities that fall within the scope of an authentication plugin.
I would better put these functionalities in a separate Capacitor plugin and then use these two plugins in combination.
Feel free to contact me with any questions.

**Comment by robingenz** [comment]
Updated dev build for testing:
```
npm i @robingenz/capacitor-firebase-authentication@0.3.9-dev.92b2bf0.1631125438
```

**Comment by erikwalle** [comment]
@robingenz naïve question before I implement: Will I ultimately get output a unique id, of the form "g123456..." that I can use to identify the user on future login? That's the format I pass to my backend.

**Comment by robingenz** [comment]
Do you know how this ID is specified/named?
I haven't tested it myself yet and have no experience with Google Play Services, so I'm asking.
You will definitely get the Firebase UID.

**Comment by erikwalle** [comment]
@robingenz On compiling in Android Studio I get:

`C:\Users\erikw\Documents\overworld\client\node_modules\@robingenz\capacitor-firebase-authentication\android\src\main\java\dev\robingenz\capacitorjs\plugins\firebase\auth\FirebaseAuthenticationPlugin.java:14: error: cannot find symbol
@CapacitorPlugin(name = "FirebaseAuthentication", requestCodes = { FacebookAuthProviderHandler.RC_FACEBOOK_AUTH })
                                                  ^
  symbol:   method requestCodes()
  location: @interface CapacitorPlugin`

Remembering your Facebook warning I changed this line:
`@CapacitorPlugin(name = "FirebaseAuthentication", requestCodes = { FacebookAuthProviderHandler.RC_FACEBOOK_AUTH })`
to:
`@CapacitorPlugin(name = "FirebaseAuthentication")`
And compilation succeeded.

But at runtime I get:

"FirebaseAuthentication.signInWithPlayGames()" is not implemented on android

I have run `npx cap sync` and synced my gradle files.

**Comment by robingenz** [comment]
Please run `npm ci` and try it again. Make sure that you have installed `@capacitor/core` version `^3.2.0`.

**Comment by erikwalle** [comment]
@robingenz Same result after `npm ci`, with `"@capacitor/core": "^3.2.2"`

**Comment by robingenz** [comment]
That is very strange.
I assume you have done the following:
```
npm ci
npx ionic cap sync android
npx ionic cap open android
```
Try deleting all temporary files in the `android` folder before that (Tip: delete the `android` folder and revert the changes via git).

Can you please share your dependencies (`package.json`)?

**Comment by erikwalle** [comment]
@robingenz Same deal, mailed you my package.json.

**Comment by robingenz** [comment]
In this case, some package must reference an old `@capacitor/core` version.

This can happen, for example, if a plugin installs `@capacitor/core` as a normal dependency instead of a peer dependency.
This is the case for `@capacitor-community/firebase-analytics` and `@openforge/capacitor-game-services`, for example.

Please try the following:
1. Delete the `node_modules` folder and the `package-lock.json` (!) file.
2. Run:
    ```
    npm install
    npx ionic cap sync android
    npx ionic cap open android
    ```

If this does not help please send me your `packge-lock.json` file too, so I can search for the package which installs the older version.

Thank you for your patience. This is an annoying problem.

**Comment by erikwalle** [comment]
@robingenz  Same problem, thanks for your support. Mailing you the lock file.

**Comment by erikwalle** [comment]
Hi Robin,

No luck. Find attached the requested file.

Thanks a lot.

Erik

**Comment by robingenz** [comment]
Alright thank you.
I am waiting for the mail.

**Comment by erikwalle** [comment]
@robingenz Sent.. did you see it?

**Comment by robingenz** [comment]
So far I have received nothing.

**Comment by erikwalle** [comment]
Maybe google has silently blocked it, here:
http://69.164.198.231/blah/package-lock.json

**Comment by robingenz** [comment]
Thanks, got it!

**Comment by robingenz** [comment]
Are you sure this is the correct `package-lock.json` file?
There is not a single Capacitor dependency listed (just search the file for `capacitor`) ... 🤔

**Comment by erikwalle** [comment]
weird, I thought it was working.

Here's the backup package-lock.json I made before following your last
steps: http://69.164.198.231/blah/package-lock.json.bak

**Comment by erikwalle** [comment]
Not sure where I got the other package-lock.json from, must have been old.
Here is the corrected file, after doing a fresh install as you suggested.

http://69.164.198.231/blah/package-lock.json

**Comment by erikwalle** [comment]
The only dependencies on capacitor/core I can see are:

   - @capacitor-community/firebase-analytics
   - @openforge/capacitor-game-services

But those seem to accept the latest version. Is there a deeper analysis
that can be done here?

**Comment by robingenz** [comment]
Basically, this looks good so far.

> npm ci
npx ionic cap sync android
npx ionic cap open android

This should have actually worked.

However, I noticed a few other things:
- `@robingenz/capacitor-firebase-authentication@0.3.10` is installed instead of `@robingenz/capacitor-firebase-authentication@0.3.9-dev.92b2bf0.1631125438`
- `@robingenz/capacitor-firebase-authentication` has no peer dependencies in your `package-lock.json` (Which npm version are you using?)

I have created a test project and tried to reproduce your error. I have installed all three capacitor plugins and get no errors when building.
So I strongly assume it's your local development environment.
Feel free to give my test project a try: https://github.com/robingenz/capacitor-firebase-authentication-pull-83-test

**Comment by erikwalle** [comment]
Hi Robin,

My problem is not with building, it's this runtime error:
"FirebaseAuthentication.signInWithPlayGames()" is not implemented on android

I've updated npm, removed node_modules and the package lock again, and
reinstalled. I am running @robingenz/capacitor-firebase-
***@***.***
The new lock file is much larger than before. Would you take another look?

http://69.164.198.231/blah/package-lock.json

Thank you,

Erik

**Comment by robingenz** [comment]
I totally misunderstood. I'm so sorry! 🤦

This should be fixed now. I created a new dev version:

```
npm i @robingenz/capacitor-firebase-authentication@0.3.10-dev.c7fd858.1631735238
```

**Comment by erikwalle** [comment]
Success! I will start work on a new release of my production build using
your code.
The outdated Play Services plugin throws errors on a lot of old devices,
I'll be able to tell you in about a month whether I see any problems in the
wild.
Congratulations on being the first in 2 years to support these seemingly
mainstream technologies. I was beginning to regret my choice of tech stack.

Thanks a lot! Btw, will you now merge this branch, or do you need anything
else?

**Comment by erikwalle** [comment]
credential:

providerId: "playgames.google.com"
[[Prototype]]: Object

user:

displayName: "rasteroid"
emailVerified: false
isAnonymous: false
photoUrl: "
https://lh3.googleusercontent.com/t0kFqc801aR_uP8J7JAqRlN2PAhouSkYwWSORsIM4JI3IgIfb4bE3R31LaLIux9sPpVr
"
providerId: "firebase"
uid: "xxx (looks fine)"

**Comment by robingenz** [comment]
Great! Glad to hear!
In this case I merge the changes and release version `0.3.11`.
Thanks for your help!
If you face any problems or have further questions, please feel free to contact me.

**Pull request merged**
